hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("./.scripts/xdph-start.sh")
  hl.exec_cmd("sleep 10 && ./.scripts/cc-audio-control.sh --enable")
end)
